// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PricePredictor.Persistence.Data;

#nullable disable

namespace PricePredictor.Infrastructure.Migrations
{
    [DbContext(typeof(PricePredictorDbContext))]
    [Migration("20260307115702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PricePredictor.Application.Models.Commodity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Commodities", (string)null);
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilityDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Avg")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("CommodityId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("RangePct")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<long>("VolumeSum")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId", "Day")
                        .IsUnique();

                    b.ToTable("Volatilities", (string)null);
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilityGold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("CommodityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<double>("LogarithmicReturn")
                        .HasColumnType("double precision");

                    b.Property<double>("LongPanicScore")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<double>("RollingVol15")
                        .HasColumnType("double precision");

                    b.Property<double>("RollingVol5")
                        .HasColumnType("double precision");

                    b.Property<double>("RollingVol60")
                        .HasColumnType("double precision");

                    b.Property<double>("ShortPanicScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("Volatility_Gold", (string)null);
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilityNaturalGas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("CommodityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<double>("LogarithmicReturn")
                        .HasColumnType("double precision");

                    b.Property<double>("LongPanicScore")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<double>("RollingVol15")
                        .HasColumnType("double precision");

                    b.Property<double>("RollingVol5")
                        .HasColumnType("double precision");

                    b.Property<double>("RollingVol60")
                        .HasColumnType("double precision");

                    b.Property<double>("ShortPanicScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("Volatility_NaturalGas", (string)null);
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilityOil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("CommodityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<double>("LogarithmicReturn")
                        .HasColumnType("double precision");

                    b.Property<double>("LongPanicScore")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<double>("RollingVol15")
                        .HasColumnType("double precision");

                    b.Property<double>("RollingVol5")
                        .HasColumnType("double precision");

                    b.Property<double>("RollingVol60")
                        .HasColumnType("double precision");

                    b.Property<double>("ShortPanicScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("Volatility_Oil", (string)null);
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilitySilver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("CommodityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<double>("LogarithmicReturn")
                        .HasColumnType("double precision");

                    b.Property<double>("LongPanicScore")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<double>("RollingVol15")
                        .HasColumnType("double precision");

                    b.Property<double>("RollingVol5")
                        .HasColumnType("double precision");

                    b.Property<double>("RollingVol60")
                        .HasColumnType("double precision");

                    b.Property<double>("ShortPanicScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("Volatility_Silver", (string)null);
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilityDaily", b =>
                {
                    b.HasOne("PricePredictor.Application.Models.Commodity", "Commodity")
                        .WithMany("DailyVolatilities")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilityGold", b =>
                {
                    b.HasOne("PricePredictor.Application.Models.Commodity", "Commodity")
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilityNaturalGas", b =>
                {
                    b.HasOne("PricePredictor.Application.Models.Commodity", "Commodity")
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilityOil", b =>
                {
                    b.HasOne("PricePredictor.Application.Models.Commodity", "Commodity")
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("PricePredictor.Application.Models.VolatilitySilver", b =>
                {
                    b.HasOne("PricePredictor.Application.Models.Commodity", "Commodity")
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commodity");
                });

            modelBuilder.Entity("PricePredictor.Application.Models.Commodity", b =>
                {
                    b.Navigation("DailyVolatilities");
                });
#pragma warning restore 612, 618
        }
    }
}

