# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\"!\n\x0eGatewayRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x1e\n\x0cGatewayReply\x12\x0e\n\x06result\x18\x01 \x01(\t2A\n\x07Gateway\x12\x36\n\x04Send\x12\x17.gateway.GatewayRequest\x1a\x15.gateway.GatewayReplyB\x1e\xaa\x02\x1bPricePredicator.App.Gatewayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\033PricePredicator.App.Gateway'
  _globals['_GATEWAYREQUEST']._serialized_start=26
  _globals['_GATEWAYREQUEST']._serialized_end=59
  _globals['_GATEWAYREPLY']._serialized_start=61
  _globals['_GATEWAYREPLY']._serialized_end=91
  _globals['_GATEWAY']._serialized_start=93
  _globals['_GATEWAY']._serialized_end=158
# @@protoc_insertion_point(module_scope)
