# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import gateway_pb2 as gateway__pb2  # relative import when used as package
except ImportError:
    import gateway_pb2 as gateway__pb2  # noqa: E402 (kept for grpc_tools compatibility)
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayStub(object):
    """Main gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVolatility = channel.unary_unary(
                '/gateway.Gateway/GetVolatility',
                request_serializer=gateway__pb2.VolatilityQueryRequest.SerializeToString,
                response_deserializer=gateway__pb2.VolatilityQueryReply.FromString,
                _registered_method=True)
        self.ExportVolatilityPeriodJson = channel.unary_unary(
                '/gateway.Gateway/ExportVolatilityPeriodJson',
                request_serializer=gateway__pb2.VolatilityPeriodRequest.SerializeToString,
                response_deserializer=gateway__pb2.JsonPayloadReply.FromString,
                _registered_method=True)
        self.ExportLatestVolatilityJson = channel.unary_unary(
                '/gateway.Gateway/ExportLatestVolatilityJson',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gateway__pb2.JsonPayloadReply.FromString,
                _registered_method=True)
        self.DownloadGoldNewsArticle = channel.unary_unary(
                '/gateway.Gateway/DownloadGoldNewsArticle',
                request_serializer=gateway__pb2.DownloadArticleRequest.SerializeToString,
                response_deserializer=gateway__pb2.DownloadArticleReply.FromString,
                _registered_method=True)
        self.GetNewestImportantArticles = channel.unary_unary(
                '/gateway.Gateway/GetNewestImportantArticles',
                request_serializer=gateway__pb2.NewestImportantArticlesRequest.SerializeToString,
                response_deserializer=gateway__pb2.NewestImportantArticlesReply.FromString,
                _registered_method=True)
        self.SubscribeLatestNews = channel.unary_stream(
                '/gateway.Gateway/SubscribeLatestNews',
                request_serializer=gateway__pb2.LatestNewsSubscriptionRequest.SerializeToString,
                response_deserializer=gateway__pb2.LatestNewsNotification.FromString,
                _registered_method=True)


class GatewayServicer(object):
    """Main gRPC service
    """

    def GetVolatility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportVolatilityPeriodJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportLatestVolatilityJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadGoldNewsArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNewestImportantArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeLatestNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVolatility': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVolatility,
                    request_deserializer=gateway__pb2.VolatilityQueryRequest.FromString,
                    response_serializer=gateway__pb2.VolatilityQueryReply.SerializeToString,
            ),
            'ExportVolatilityPeriodJson': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportVolatilityPeriodJson,
                    request_deserializer=gateway__pb2.VolatilityPeriodRequest.FromString,
                    response_serializer=gateway__pb2.JsonPayloadReply.SerializeToString,
            ),
            'ExportLatestVolatilityJson': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportLatestVolatilityJson,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gateway__pb2.JsonPayloadReply.SerializeToString,
            ),
            'DownloadGoldNewsArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadGoldNewsArticle,
                    request_deserializer=gateway__pb2.DownloadArticleRequest.FromString,
                    response_serializer=gateway__pb2.DownloadArticleReply.SerializeToString,
            ),
            'GetNewestImportantArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNewestImportantArticles,
                    request_deserializer=gateway__pb2.NewestImportantArticlesRequest.FromString,
                    response_serializer=gateway__pb2.NewestImportantArticlesReply.SerializeToString,
            ),
            'SubscribeLatestNews': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeLatestNews,
                    request_deserializer=gateway__pb2.LatestNewsSubscriptionRequest.FromString,
                    response_serializer=gateway__pb2.LatestNewsNotification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gateway.Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gateway(object):
    """Main gRPC service
    """

    @staticmethod
    def GetVolatility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.Gateway/GetVolatility',
            gateway__pb2.VolatilityQueryRequest.SerializeToString,
            gateway__pb2.VolatilityQueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportVolatilityPeriodJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.Gateway/ExportVolatilityPeriodJson',
            gateway__pb2.VolatilityPeriodRequest.SerializeToString,
            gateway__pb2.JsonPayloadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportLatestVolatilityJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.Gateway/ExportLatestVolatilityJson',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gateway__pb2.JsonPayloadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadGoldNewsArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.Gateway/DownloadGoldNewsArticle',
            gateway__pb2.DownloadArticleRequest.SerializeToString,
            gateway__pb2.DownloadArticleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNewestImportantArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.Gateway/GetNewestImportantArticles',
            gateway__pb2.NewestImportantArticlesRequest.SerializeToString,
            gateway__pb2.NewestImportantArticlesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeLatestNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gateway.Gateway/SubscribeLatestNews',
            gateway__pb2.LatestNewsSubscriptionRequest.SerializeToString,
            gateway__pb2.LatestNewsNotification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
